src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/listener/EntityListener.java

This will allow players state to get reset if they are in anything but NORMAL mode on that certain group

Promoteplayer

---

src/vg/civcraft/mc/citadel/listener/EntityListener.java

https://github.com/Civcraft/NameLayer/pull/69
This just updates ctr and ctf to allow a default group

Allow player to set default group

---

src/vg/civcraft/mc/citadel/command/commands/Fortification.java

I think this will fix the null issue from /ctfortify
Was not able to test this

Update Fortification.java should fix issue #69

---

src/vg/civcraft/mc/citadel/Citadel.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java

removed a couple invalid imports so it should build now

Fixed an issue where TealNerd is a lying little bitch

---

src/vg/civcraft/mc/citadel/listener/BlockListener.java

~~Fix #89 with ... Also requires a small change to NameLayer~~
~~https://github.com/Civcraft/Citadel/commit/c3d4738900fef8b145b4c7bef321b68ddab08b16~~
Fix #88 with 
https://github.com/Civcraft/Citadel/commit/d27aec72184bbb9cb6d15c485a15abea5fda4fc0

Fix #88 and #89

---

src/vg/civcraft/mc/citadel/listener/BlockListener.java

I tested it, seems to be working. More testing should be done on civtest.

Fix for Pistons

---

src/vg/civcraft/mc/citadel/command/commands/Acid.java

fix issue with acid blocks

---

src/vg/civcraft/mc/citadel/listener/BlockListener.java

Also add in extra logging for exceptions in blocklistener
#113

Fix issue with quietly exiting reinforcement mode

---

pom.xml
src/vg/civcraft/mc/citadel/command/commands/Fortification.java
src/vg/civcraft/mc/citadel/command/commands/Reinforce.java

Adressing https://github.com/Civcraft/Citadel/issues/116
@rourke750

Let op /ctf and /ctr to any group

---

plugin.yml
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/command/CommandHandler.java
src/vg/civcraft/mc/citadel/command/commands/AreaReinforce.java

Admin crime tool   @rourke750  could you review this, please?

Areareinforcements for admins

---

config.yml

@rourke750 
Can I just merge this or do I need to do anything else? That's for jacky.

Adding bedrock reinforcement

---

pom.xml
src/vg/civcraft/mc/citadel/command/commands/Acid.java

Cleaning up some code that can cause "ghost" reinforcements.

Fixing some ghost blocks

---

pom.xml
src/vg/civcraft/mc/citadel/listener/BlockListener.java

Fix for https://www.reddit.com/r/Civcraft/comments/3sntot/naively_implemented_citadel_fix_is_in_process_of/

Patch for chunk load / flush problem

---

src/vg/civcraft/mc/citadel/command/commands/Materials.java

Adds an additional line with maturation time.
Small addition, already tested and working on Devoted.

Adding maturation time to /ctm

---

config.yml
src/vg/civcraft/mc/citadel/CitadelConfigManager.java
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/command/commands/Acid.java
src/vg/civcraft/mc/citadel/database/CitadelReinforcementData.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/reinforcement/MultiBlockReinforcement.java
src/vg/civcraft/mc/citadel/reinforcement/NaturalReinforcement.java
src/vg/civcraft/mc/citadel/reinforcement/NullReinforcement.java
src/vg/civcraft/mc/citadel/reinforcement/PlayerReinforcement.java
src/vg/civcraft/mc/citadel/reinforcement/Reinforcement.java
src/vg/civcraft/mc/citadel/reinforcementtypes/ReinforcementType.java

Updated for latest changes. Should work fine on civ-main-stream servers; anyone who used the prior fork or Devoted's fork will not have a smooth upgrade.
Doesn't impact CivCraft's master, though, this merge should be clean and upgrade clean.

Rebased sketch of splitting out acid timer as a separate thing. 

---

.gitignore
config.yml
pom.xml
src/vg/civcraft/mc/citadel/CitadelConfigManager.java
src/vg/civcraft/mc/citadel/ReinforcementManager.java
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/listener/EntityListener.java
src/vg/civcraft/mc/citadel/reinforcement/PlayerReinforcement.java

Integration of cullTimes for reinforcements with NameLayer2.5.43

---

src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/listener/EntityListener.java

- Adds Entity Reinforcement for Item Frames and Paintings(1x1) #82 
- Addresses npe in Utility.java
Code review is welcome.

Address Civcraft/Citadel#82

---

pom.xml
src/vg/civcraft/mc/citadel/Citadel.java
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/command/commands/Acid.java
src/vg/civcraft/mc/citadel/command/commands/Fortification.java
src/vg/civcraft/mc/citadel/command/commands/Reinforce.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/listener/EntityListener.java
src/vg/civcraft/mc/citadel/reinforcement/PlayerReinforcement.java

Let's Citadel use the new functionality added with https://github.com/Civcraft/NameLayer/pull/191
Should be merged after the NameLayer PR is merged.

Rework permissions

---

config.yml
pom.xml
src/vg/civcraft/mc/citadel/CitadelConfigManager.java
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/listener/EntityListener.java

Everything Citadel related mentioned here https://github.com/DevotedMC/Citadel/issues/16
Diff is kinda fucked due to some unintended formatting, sorry for that. Haven't tested this yet, but will do so tomorrow.

Newfriend friendly Citadel according to shadeds suggestions

---

.gitignore
config.yml
src/vg/civcraft/mc/citadel/Citadel.java
src/vg/civcraft/mc/citadel/CitadelConfigManager.java
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/command/commands/AreaReinforce.java
src/vg/civcraft/mc/citadel/listener/BlockListener.java
src/vg/civcraft/mc/citadel/listener/EntityListener.java
src/vg/civcraft/mc/citadel/reinforcementtypes/ExclusiveReinforcementType.java

Take 3 or 4 or something. Let's just get this merged in before we drift further.
It's a solid feature and will give us much needed flexibility in 3.0
@Maxopoly lemme know if you see anything wrong with this pull

Exclusives

---

config.yml

As discussed, all types and tiers.

---

.editorconfig
config.yml
pom.xml
src/vg/civcraft/mc/citadel/CitadelConfigManager.java
src/vg/civcraft/mc/citadel/Utility.java
src/vg/civcraft/mc/citadel/command/commands/Acid.java
src/vg/civcraft/mc/citadel/command/commands/SetLogging.java

for each config item. Needs testing but should resolve that issue. Also includes minor fix for extremely low probability chance that when breaking a 0 health reinforced block, the reinforcement would drop, due to how Random.nextDouble() works.

Addressing some less then great logspamming due to what gets logged
